INSERT INTO INDIVIDUO(ID,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,NOMBRE_USUARIO,EDAD) VALUES(1,'LUKE','SKYWALKER','GARCIA','SOY_TU_PADRE',22);
INSERT INTO INDIVIDUO(ID,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,NOMBRE_USUARIO,EDAD) VALUES(2,'LEIA','SKYWALKER','MARTINEZ','I_AM_YOUR_GENERAL',21);
INSERT INTO INDIVIDUO(ID,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,NOMBRE_USUARIO,EDAD) VALUES(3,'HAN','SOLO','SOTO','ILOVEMILLENARYHALCON',30);
INSERT INTO INDIVIDUO(ID,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,NOMBRE_USUARIO,EDAD) VALUES(4,'CHEWBACA','ARGHHH','CABALLERO','CHEIW',100);